# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #runs-on: ubuntu-18.04
    container: 
      image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
      options: --user root --privileged 
      volumes: 
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
    
    #entrypoint: /usr/sbin/init
    #args:
    #  - 'systemctl start httpd.service'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      #- name: Startup
      #  run: |
      #   /usr/sbin/init systemctl start httpd.service

      - name: Install CVMFS
        run: |
          set -x
          yum clean all
          yum --disablerepo="epel" update nss 
          echo y > answer.txt
          yum install https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm < answer.txt
          yum install -y cvmfs

      - name: Mount and configure basics
        run: |
          set -x
          #exec /usr/sbin/init && systemctl restart autofs
          #systemctl enable autofs
          #cvmfs_config setup
          mkdir -p /cvmfs/cvmfs-config.cern.ch
          mount -t cvmfs cvmfs-config.cern.ch /cvmfs/cvmfs-config.cern.ch
          touch /etc/cvmfs/default.local
          echo CVMFS_REPOSITORIES=cms.cern.ch | tee /etc/cvmfs/default.local
          echo CVMFS_CLIENT_PROFILE=single | tee -a /etc/cvmfs/default.local
          #/usr/bin/systemctl restart autofs &
          #exec /usr/sbin/init
          #cvmfs_config probe

      - name: Mount cms.cern.ch and check contents
        run: |
          set -x
          #mount -t cvmfs cms.cern.ch /cvmfs/cms.cern.ch
          ls -lrth .
          ls -lrth /
          ls -lrth /cvmfs
          #mkdir -p /cvmfs/cms.cern.ch
          #mount -t cvmfs cms.cern.ch /cvmfs/cms.cern.ch
          ls -lrth /cvmfs/cms.cern.ch/

      #- name: Install gcc packages
      #  run: |
      #    eval 'which g++'
      #    sudo apt-get install g++-multilib

      - name: Set up environment to install LEAF
        run: |
          set -x
          export VO_CMS_SW_DIR=/cvmfs/cms.cern.ch
          export SCRAM_ARCH=slc7_amd64_gcc700
          shopt -s expand_aliases
          source /cvmfs/cms.cern.ch/cmsset_default.sh
          eval 'which g++'
          echo $PATH

      - name: Download get_leaf.sh
        run: wget https://raw.githubusercontent.com/reimersa/LEAF/master/get_leaf.sh

      - name: Get and install LEAF
        run: |
          set -x
          sudo ln -sf bash /bin/sh
          echo $PATH
          eval 'which g++'
          shopt -s expand_aliases
          source get_leaf.sh